### PR TITLE
Set MQTT Actor Power Level to Zero if Switched Off

### PR DESCRIPTION
**Pull request by chappo**
Set power level to 0 if actor turned off

### CODE REVIEW

**Comment by avollkopf** [comment]
For some reason, I changed it to this behavior in the past. It may cause an issue for some users, if I change it. 

Proposal: I add one parameter to the actor if power should be set to 0 if actor is switched off or if it should remain at given power. This could be added to the actor extensions.

**Comment by chappo** [comment]
Parameter would be an acceptable solution. I would think that there would be a risk of dry firing if the actor stays at the last power setting though

**Comment by avollkopf** [comment]
But what about switching the actor on? If it will be set to 0 when switching it off, it would need to be set to 100 if switched on instead of remaining at the former power setting.

**Comment by lalo-uy** [comment]
I vote for leave the power seting.
What when set power level while off, will toun on?
Will always be 2 librarys on this subject.

**Comment by avollkopf** [comment]
The only thing I could imagine: 

default setting for a sensor -> leave it as it is
Optional if pramter set to yes: set to 0  on power off and set to 100% on power on. 

However, 
I don't see a real benefit.

**Comment by chappo** [comment]
I would have thought you would save the power level in the variable. Only the MQTT update would show zero ie off? 

As you say happy to go with a variable to change that feature - I would like to be able to just set the payload variable to show only the power level - ie just have {power} exposed with zero = OFF. 

In my instance I have a 4-20ma SSR controlling 0-100%. I would need to process both variables before changing the SSR (It's not an issue for me anyway as I have Bacnet DDC controllers providing other safety features).

**Comment by avollkopf** [comment]
I reviewed it in more detail and it should work-> switching the actor on should send also the old power value

-> I will merge it into the development branch for testing

**Comment by avollkopf** [comment]
i've been testing this with the regular mqtt actor and it is working.

example: 
- set power to 50%, switch actor on -> mqtt actor will be set to on with 50% power
- switch actor off via dashboard actor item: mqtt actor will be switched off and set to 0% (power on dashboard icon remains at 50%)
- switch actor on via dashboard icon: mqtt actor will be switched on with 50% power

**Pull request merged**
