### PR TITLE
Update readme to include more info about the project

### PR DESCRIPTION
**Pull request by papauorg**
When I had my first contact with CraftBeerPi I had a really hard time to find the information about the project and documentation. Especially because the readme of the project contains only one info and it is a link to a documentation page that does not help at all.

What helped was a forum thread that I found which linked to your documentation page. But finding that was a coincidence.

With this PR I included some more info about the project and the link to the working documentation so the repo looks more 'alive'. Generally giving the readme file some :heart:.

Btw, is there a separate repo for the documentation? Is it publicly accessible?

Maybe include some links on where to get help? What would those be?

### CODE REVIEW

**Comment by avollkopf** [comment]
I also thought that the readme should be updated. I am basically fine, but prefer to add the details on how to create a docker to the documentation as a new chapter

**Comment by papauorg** [comment]
I removed the Docker part from the readme. Unfortunately I don't know and didn't find where I can put something in the documentation. Maybe this would be a good topic for the readme? :wink:

**Comment by avollkopf** [comment]
@papauorg There is no direct way to change the documentation. 

1) You need to sign up for gitbook (which is free).
2) send me your email and I will add you to the contributors of the gitbook. (not sure if you are on Facebook and can send me a PM). Otherwise you will find my email in the setup.py of the plugins :-)

One other thing that puzzles me about the Docker:
1. Is there a way to modify the config.yaml if you want to enable mqtt inside the docker
2. If not, is it possible to set sort of environment variables for an existing docker where cbpi could retrieve the mqtt configuration from? I've seen similar things for other dockers.
3. If not, we would need to think about moving the mqtt parameters to the config.json

**Comment by papauorg** [comment]
> send me your email and I will add you to the contributors of the gitbook.

Yeah I can do that. But wouldn't it be cooler to allow people to send pull requests to update the documentation? As far as I know gitbook can sync with a git repository. I think you can even sync an existing gitbook with a new repository. How about a `avollkopf/craftbeerpi4_docs` repository or something like that?

> not sure if you are on Facebook

No ;-)

> 1. Is there a way to modify the config.yaml if you want to enable mqtt inside the docker

Well you could change it within the container. The problem is that when you delete the container and start another one (e.g. when updating a version), the change is gone. That's why in my sample I created a volume on the host and mounted it in the container. This means that the files persist during a recreation of the container and can be edited from outside the container.

image
Here you see that a folder `config` (green) in the current working directory of the host will be made available under the path `/cbpi/config` (blue) in the container. Everything what's inside the hosts `config` folder is available in the container, too. As far as I can see, both config files you mentioned are in this directory so I think it does not matter in which of those files the config parameters are included.

Does this answer your question?

> 2. If not, is it possible to set sort of environment variables for an existing docker where cbpi could retrieve the mqtt configuration from? I've seen similar things for other dockers.
Yes you can also set environment variables when starting a container. This is even a common practice when using containers and a lot of products support configuration via environment variables because of it. It's easy to set them e.g. when using an orchestrator like `docker-compose`. So it would be cool to have this, but it is not required for changing the mqtt setting in cbpi. See above.

> 3. If not, we would need to think about moving the mqtt parameters to the config.json

I don't see how that would be different - at least not for running the docker container. Both files are in the same folder that can be mounted as described above. In which file the setting is located does not matter. At least if I understood your question correctly.

**Comment by avollkopf** [comment]
> Yeah I can do that. But wouldn't it be cooler to allow people to send pull requests to update the documentation? As far as I know gitbook can sync with a git repository. I think you can even sync an existing gitbook with a new repository. How about a `avollkopf/craftbeerpi4_docs` repository or something like that?

Currently, the documentation is only on gitbook w/o a link to github. A link seems to be possible, but I have no experience with that. I might dig into that next year when/if I have more time. For now, I need to stick to the gitbook solution.

>Here you see that a folder config (green) in the current working directory of the host will be made available under the path /cbpi/config (blue) in the container. Everything what's inside the hosts config folder is available in the container, too. As far as I can see, both config files you mentioned are in this directory so I think it does not matter in which of those files the config parameters are included.
>
>Does this answer your question?

That sounds great. Anyhow I won't need it personally. But other folks who want to run it in a container might be interested on how to configure it and maintain the configuration. I think, that the backup/restore function from cbpi should also do the job.

I will merge that later but keep the Docker image part. Only the instructions on how to create a Docker should go into the documentation.

**Comment by papauorg** [comment]
>I will merge that later but keep the Docker image part. Only the instructions on how to create a Docker should go into the documentation.

I'm not sure I understand. Do you want me to change something in the PR? If so please explain what changes you want.

**Pull request merged**
