### PR TITLE
Add Influxdb-cloud connection and log for actor, fermenter and kettles

### PR DESCRIPTION
**Pull request by pascal1404**
Hi Alex, I added an option to use the influxdb cloud to store your data and add logs for kettle and fermenter target temp and for actor power.

### CODE REVIEW

**Comment by avollkopf** [comment]
@pascal1404 I will look into it. However, the updates on target temps are sort of redundant as this has been already implemented via the [kettlesensor plugin](https://github.com/avollkopf/cbpi4-KettleSensor) which can also send power for the kettle and status for the fermenter (heat, cool or nothing). This plugin is also taking care of reduced data logging. It basically sends only data if the value has changed or after 1 minute or so. Therefore, I would prefere to not include this into the controllers, since not everybody wants to log it. With the sensor plugin, one can decide if values should be logged or not by creating the 'sensor' or not.

**Comment by avollkopf** [comment]
One older Example, where you can see the target temp and power log for the kettle

Screenshot 2022-02-06 112441

**Comment by avollkopf** [comment]
Just ralized, that power will be also logged fo all the actors. Same here, they cannot be seen on the analytcs page and user cannot decide if he wants to log actor power which is in most cases probably not required (except for kettle and maybe fermenter (-> heating, cooling,..)

**Comment by pascal1404** [comment]
I wasn't aware of this plugin. It makes sense to let the user decide which values they want to log. I will remove these changes and push a version were only the influxdb cloud changes are in.

**Comment by avollkopf** [comment]
BTW, do you have any experience with influxdb 2.0 or a chance to test it. So far, I had no time to install it on my NAS and test the new authentication.

**Comment by pascal1404** [comment]
> BTW, do you have any experience with influxdb 2.0 or a chance to test it. So far, I had no time to install it on my NAS and test the new authentication.

I don't understand influxdb 2.0 perfectly, but if you want to use influxdb cloud you have to work with it. So yes I have tested it with my setup.

**Pull request merged**
