### PR TITLE
Build docker image for master and development branches

### PR DESCRIPTION
**Pull request by papauorg**
I created a repository that contains a `Dockerfile` to create a craftbeerpi4 image according to your documentation page (https://openbrewing.gitbook.io/craftbeerpi4_support/master/server-installation). Thanks for that by the way.

You can find the repository I created here: https://github.com/papauorg/craftbeerpi4-docker.

After sucessfully creating the image I figured that the build process and image should be part of the repository that is actually maintained. So here is my suggestion for a changed Docker image.

I also created the config for a github action that should work in your repository after merging. I tried in my fork, before.
It does the following:
- Builds the docker image for the master and development branches (and main, in case it is renamed to the new default)
- For master it tags the image as `latest` and `v0.0.0.0` - where `0.0.0.0` is the version number from `cbpi/__init__.py`
- For all other builds, it tags the image with 'dev'. This only affects the build when pushing changes to the development branch currently. This gives us a kind oft preview/unstable image e.g. for testing.
- The image is uploaded to the github image registry that is associated with the repository. This would be `ghcr.io/avollkopf/craftbeerpi4` after merging.
- Images are created for `amd64` and `arm64` architectures. I couldn't get it to build for `arm/v7`. I don't know enough about python I guess. But for the 64bit raspberry pi OS it works.

This would lead to continuously updated, runnable images that could easily be consumed by users of craftbeerpi4.

The above mentioned repository also contains a readme that explains how to use the image. I wasn't sure if I should put that information in the readme of your repo with this PR because it's so empty :). But I could add that commit if you want.

Would be awesome to have those images in the 'main' repo!

Please let me know what you think!

Best regards,
Philipp

### CODE REVIEW

**Comment by avollkopf** [comment]
This sounds good to me. However, I have no experience with any sort of docker creation. What about the Plugins? There is currently no automated way to install plugins like it used to be on cbpi3. Is it possible to install plugins inside the docker?

**Comment by papauorg** [comment]
The image in this version does not contain functionality to install plugins. But that would be something that can be extended.

My goal is to have the software setup including the configuration for my brewery in version control and be able to start or recreate it using `docker-compose`. It would be great or even a requirement that plugins are a part of this. I'm just not entirely sure what would be the best solution for this. Here are some ideas:

1.) __Build a custom Dockerimage based on the one suggested in the PR__
When someone wants to use craftbeerpi4 in a docker image, they could create their own `Dockerfile` that has the 'official' one as a base image. Within that file they could install plugins from different sources, the same way as they would do directly on a raspberry via `pip install ... `.

Sample:
```Dockerfile
FROM ghcr.io/avollkopf/craftbeerpi4:v4.0.0.xx

RUN pip install --no-cache-dir cbpi-plugin-xxx && cbpi add cbpi-plugin-xxx
```
I have not tried this, yet. But something like this would be my prefered approach. Also it can already be done with the image of this PR.

2.) __Include an installation script in the image that installs plugins based on a config__
Not sure if this is a good idea but we could put an installation script in the image that is run before cbpi start is executed every time the container starts. It could read some file (maybe something like a requirements.txt) and install all that is included there. After read another file and install the plugins in cbpi.

Sample:
cbpi-python-packages.txt
```txt
https://github.com/avollkopf/cbpi4-pt100x/archive/main.zip
```
cbpi-plugins.txt
```
cbpi4-pt100x
```

And then, when starting, they could mount the files as volumes and the image could automatically install the plugins:
```bash
docker run -d -v "$(pwd)/cbpi-python-packages.txt:/cbpi-python-packages.txt" -v "$(pwd)/cbpi-plugins.txt:/cbpi-plugins.txt" ghcr.io/avollkopf/craftbeerpi4:latest
```
I think this approach places the maintenance effort on this repository and is less flexible. Also this would have to be implemented in this repo first because it has to be part of the image. I'd personally prefer the first approach.


Regardless of which approach is used it's always based on a runnable image. So I suggest to create the image first before continuing further.

**Comment by avollkopf** [comment]
Sounds good. I will merge that irst into the development branch for testing and later to the main branch.

**Comment by avollkopf** [comment]
@papauorg There seems to b eissues with the PR / workflow. I get this issue reported:

`buildx failed with: error: failed to solve: process "/bin/sh -c pip3 install --no-cache-dir /cbpi-src" did not complete successfully: exit code: 1`

**Comment by avollkopf** [comment]
and here is the log

[logs_2.zip](https://github.com/avollkopf/craftbeerpi4/files/7613495/logs_2.zip)

**Comment by papauorg** [comment]
Oh, ok. Now that the action is available, it's also easier to investigate and test __before__ a PR is merged.

I'll have a look and create a new PR with a fix.

**Comment by avollkopf** [comment]
Somehow building psutil seems to fail

**Comment by papauorg** [comment]
@avollkopf Is fixed in the PR #9

**Pull request merged**
